<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "dashboard"
 *
 * Auto generated by Extension Builder 2015-06-18
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Dashboard',
	'description' => 'Customizable dashboard which can display dashboard widgets.',
	'category' => 'be',
	'author' => '',
	'author_email' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.2.0-7.99.99',
            'sys_action' => '7.6.0-7.6.99'
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);